// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module("Fish", []);

  app.controller("FishController", [
    "$scope", "LeapService", "FishService", function($scope, LeapService, FishService) {
      var lastFlapDirection, lastFlapTime;
      $scope.base_pose = {};
      $scope.paused = true;
      $scope.tilt = 0;
      $scope.activeHandId = undefiend;
      LeapService.on('noseUp', function() {
        return FishService.enqueue('noseUp');
      });
      LeapService.on('noseDown', function() {
        return FishService.enqueue('noseDown');
      });
      LeapService.on('noseSteady', function() {
        return FishService.enqueue('noseSteady');
      });
      $scope.intializeFromCurrentPose = function() {
        console.log('would initalize now');
        return $scope.base_pose = {};
      };
      LeapController.on('engage', function(hand) {
        $scope.intializeFromCurrentPose(hand);
        FishService.clearQueue();
        return FishService.start();
      });
      LeapController.on('disengage', function() {
        return FishService.stop();
      });
      lastFlapTime = undefiend;
      lastFlapDirection = undefiend;
      $scope.autoFlap = function(frame) {
        var elapsedTime;
        elapsedTime = new Date() - lastFlapTime;
        if (lastFlapDirection === 'right' && elapsedTime > frame.rightFlapTime) {
          FishService.enqueue('flapLeft');
          lastFlapDirection === 'left';
          lastFlapTime = new Date();
        }
        if (lastFlapDirection === 'left' && elapsedTime > frame.leftFlapTime) {
          FishService.enqueue('flapRight');
          lastFlapDirection === 'right';
          return lastFlapTime = new Date();
        }
      };
      return Leap.on('frame', function(frame) {
        if (!FishService.going) {
          return;
        }
        if (FishService.queue.length === 0) {
          return $scope.autoFlap(frame);
        }
      });
    }
  ]);

}).call(this);
