// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module("Fish", []);

  app.controller("FishController", [
    "$scope", "LeapService", "FishService", function($scope, LeapService, FishService) {
      var lastCommandTime, lastFlapDirection, lastFlapTime;
      $scope.base_pose = {};
      $scope.paused = true;
      $scope.tilt = 0;
      $scope.activeHandId = void 0;
      LeapService.on('noseUp', function() {
        FishService.enqueue('stop');
        return $scope.noseState = 'noseUp';
      });
      LeapService.on('noseDown', function() {
        FishService.enqueue('stop');
        return $scope.noseState = 'noseDown';
      });
      LeapService.on('noseSteady', function() {
        FishService.enqueue('stop');
        return $scope.noseState = 'noseSteady';
      });
      $scope.intializeFromCurrentPose = function() {
        console.log('would initalize now');
        return $scope.base_pose = {};
      };
      LeapService.on('engage', function(hand) {
        $scope.intializeFromCurrentPose(hand);
        FishService.queue = [];
        return FishService.start();
      });
      LeapService.on('disengage', function() {
        return FishService.stop();
      });
      lastFlapTime = new Date();
      lastFlapDirection = 'Right';
      $scope.autoFlap = function(frame) {
        var elapsedTime;
        elapsedTime = new Date() - lastFlapTime;
        console.log('autoflap');
        if (lastFlapDirection === 'Right' && elapsedTime > frame.rightFlapTime) {
          return $scope.flap('Left');
        } else if (lastFlapDirection === 'Left' && elapsedTime > frame.leftFlapTime) {
          return $scope.flap('Right');
        }
      };
      $scope.flap = function(direction) {
        console.log('flap', direction);
        FishService.enqueue('stop');
        FishService.enqueue("flap" + direction);
        lastFlapDirection = direction;
        return lastFlapTime = new Date();
      };
      lastCommandTime = new Date();
      $scope.autoNose = function() {
        var elapsedTime;
        elapsedTime = new Date() - lastCommandTime;
        if (elapsedTime > 200) {
          FishService.enqueue($scope.noseState);
          return lastCommandTime = new Date();
        }
      };
      return LeapService.on('frame', function(frame) {
        if (!FishService.going) {
          return;
        }
        if ($scope.noseState === 'noseSteady') {
          $scope.autoFlap(frame);
        } else {
          $scope.autoNose(frame);
        }
        $scope.history = FishService.history;
        $scope.frame = frame;
        return $scope.$digest();
      });
    }
  ]);

}).call(this);
