// Generated by CoffeeScript 1.6.3
(function() {
  app.factory('FishService', [
    function() {
      var SerialPort, fishService, go, queueCommandToSerialCommand, serialPort;
      SerialPort = require("serialport").SerialPort;
      serialPort = new SerialPort("/dev/tty.usbmodem12341", {
        baudrate: 57600
      });
      serialPort.on('open', function() {
        return console.log('serial port opened', arguments);
      });
      queueCommandToSerialCommand = {
        noseUp: 'w',
        noseDown: 's',
        flapLeft: 'd',
        flapRight: 'a',
        stop: 'q'
      };
      go = function() {
        var command, serialCommand;
        if (command = fishService.queue.shift()) {
          if (!(serialCommand = queueCommandToSerialCommand[command])) {
            console.warn("Unknown Command: ", command);
            return;
          }
          serialPort.write("" + serialCommand + "\r\t", function(err, results) {});
        } else {

        }
        if (fishService.going) {
          return setTimeout(go, 20);
        }
      };
      fishService = {
        going: false,
        queue: [],
        history: [],
        start: function() {
          fishService.going = true;
          return go();
        },
        stop: function() {
          fishService.queue = [];
          fishService.enqueue('stop');
          return fishService.going = false;
        },
        enqueue: function(command) {
          fishService.queue.push(command);
          return fishService.history.unshift(command);
        }
      };
      return fishService;
    }
  ]);

}).call(this);
