// Generated by CoffeeScript 1.6.3
(function() {
  app.factory("LeapService", [
    function() {
      var controller, engagedHandId, previousValidHandIds;
      console.log("connecting");
      controller = new Leap.Controller();
      controller.on("connect", function() {
        return console.log("Successfully connected.");
      });
      controller.on("deviceDisconnected", function() {
        return console.log("A Leap device has been disconnected.");
      });
      previousValidHandIds = [];
      controller.on("frame", function() {
        var id, newValidHandIds, _i, _j, _len, _len1, _results;
        newValidHandIds = controller.lastValidFrame.hands.map(function(hand) {
          return hand.id;
        });
        for (_i = 0, _len = previousValidHandIds.length; _i < _len; _i++) {
          id = previousValidHandIds[_i];
          if (!newValidHandIds.includes(id)) {
            previousValidHandIds.remove(id);
            controller.emit('lostHand', id);
          }
        }
        _results = [];
        for (_j = 0, _len1 = newValidHandIds.length; _j < _len1; _j++) {
          id = newValidHandIds[_j];
          if (!previousValidHandIds.includes(id)) {
            previousValidHandIds.push(id);
            _results.push(controller.emit('foundHand', id));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
      engagedHandId = void 0;
      controller.addStep(function(frame) {
        var hand, _i, _len, _ref;
        if (!engagedHandId) {
          _ref = frame.hands;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            hand = _ref[_i];
            if (hand.pointables.length > 1) {
              console.log('engaging hand', hand.id);
              engagedHandId = hand.id;
              controller.emit('engage', hand);
            }
          }
        } else if (engagedHandId && engagedHand.pointables < 1) {
          console.log('disengaging hand', engagedHandId);
          engagedHandId = void 0;
          controller.emit('disengage', engagedHandId);
        }
        if (engagedHandId) {
          return frame.activeHand = frame.hands.getById(engagedHandId);
        }
      });
      window.PitchHandler = function() {
        var activationAngle, state, zeroAngle;
        zeroAngle = 0;
        activationAngle = 0.5;
        state = void 0;
        this.setZeroAngle = function(angle) {
          return zeroAngle = angle;
        };
        Hand.prototype.adjustedPitch = function() {
          return this.pitch() - zeroAngle;
        };
        return this.onFrame = function(frame) {
          if (state !== 'noseDown' && frame.activeHand.adjustedPitch() > activationAngle) {
            state = 'noseDown';
            return controller.emit('noseDown');
          } else if (state !== 'noseUp' && frame.activeHand.adjustedPitch() > activationAngle) {
            state = 'noseUp';
            return controller.emit('noseUp');
          } else if (state !== 'noseSteady') {
            state = 'noseSteady';
            return controller.emit('noseSteady');
          }
        };
      };
      controller.addStep(window.PitchHandler.onFrame);
      controller.addStep(function(frame) {
        frame.baseFlapTime = 1000 + frame.activeHand.z();
        frame.leftFlapTime = frame.baseFlapTime + frame.activeHand.x();
        return frame.rightFlapTime = frame.baseFlapTime - frame.activeHand.x();
      });
      controller.connect();
      return controller;
    }
  ]);

}).call(this);
